version: '3.8'
services:
  db:
    image: mysql:8
    container_name: nestjs-star-prod-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    restart: always
    networks:
      - app
  server:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: nestjs-star-prod-server
    restart: always
    volumes:
      - appdata:/usr/src/app
    ports:
      - ${APP_HOST_PORT_PROD}:${APP_CONTAINER_PORT}
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh db:${DB_CONTAINER_PORT} -t 15
        node ./dist/main.js
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  dbdata:
    driver: local
  appdata:
    driver: local
