version: '3.8'
services:
  db:
    image: mysql:8
    container_name: point-nest-dev-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    restart: always
    networks:
      - app
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: point-nest-dev-server
    restart: always
    volumes:
      - appdata:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 15
        yarn start:dev
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local
